"""NL/FR/EN-inhoud voor de Adaptiviteit Systeemscan."""

LANGUAGE_NAMES = {"nl": "Nederlands", "fr": "Français", "en": "English"}

UI_TEXTS = {
    "nl": {
        "title": "Adaptiviteit Systeemscan", "intro": "Ontdek welke individuele, team- en organisatiefactoren jouw adaptief gedrag ondersteunen of belemmeren.",
        "details_step": "Stap 1 · Je gegevens", "details_title": "Vertel ons kort wie je bent", "details_intro": "Vul de systeemscan in en ontdek wat jij en je omgeving kunnen doen om adaptiever te worden.",
        "name": "Naam", "email": "E-mailadres (optioneel)", "email_help": "We bewaren dit alleen zodat we je resultaat later eventueel kunnen bezorgen. Er wordt nu geen e-mail verstuurd.", "role": "Functie", "organisation": "Organisatie", "start": "Start vragenlijst",
        "manager_question": "Geef je rechtstreeks leiding aan medewerkers?", "yes": "Ja", "no": "Nee", "manager_required": "Duid aan of je rechtstreeks leiding geeft aan medewerkers.",
        "self_leadership_title": "Jouw eigen leiderschap", "self_leadership_intro": "Vul dit in met het team waaraan je leiding geeft in gedachten.",
        "own_manager_title": "Jouw eigen leidinggevende", "own_manager_intro": "Hieronder vragen we je ook om enkele vragen over je eigen leidinggevende in te vullen.",
        "self_leadership_result": "Jouw adaptief leiderschap", "self_leadership_result_intro": "Deze aanvullende score vat samen hoe je je eigen leiderschap ervaart in het team waaraan je leiding geeft.",
        "self_benchmark_unavailable": "Benchmarkgegevens voor eigen leiderschap zijn momenteel nog niet beschikbaar.", "self_recommendation": "Aanbeveling", "self_recommendation_text": "Gebruik de drie subdimensies als gespreksstarter: behoud wat al sterk is en kies één concreet gedrag binnen de laagst scorende subdimensie om verder te oefenen en feedback op te vragen.",
        "part": "Deel {current} van 3", "part_individual": "Individuele basis", "part_team": "Team & leidinggevende", "part_organisation": "Organisatie",
        "part_instruction": "Duid voor elke uitspraak aan in welke mate je ermee akkoord gaat.", "previous": "Vorige", "next": "Volgende", "show_result": "Toon mijn resultaat", "missing": "Vul alle vragen in dit deel in.", "complete": "Dit deel is volledig ingevuld.",
        "scale": ["Helemaal oneens", "Oneens", "Neutraal", "Eens", "Helemaal eens"],
        "profile_pill": "Jouw systeemprofiel", "thanks": "Bedankt voor je deelname", "result_intro": "Je resultaten tonen welke factoren op individueel, team- en organisatieniveau jouw adaptief gedrag vandaag ondersteunen of belemmeren.",
        "model": "Het overkoepelende model", "stands_out": "Wat valt op?", "strongest": "Sterkste ondersteunende factor", "development": "Grootste ontwikkelkans",
        "higher_than": "Hoger dan ongeveer {p}% van de referentiegroep", "lower_context": "Deze factor wordt relatief minder sterk ervaren en kan een zinvolle ontwikkelhefboom zijn.",
        "summary_note": "Gebruik vooral het patroon over de drie niveaus als vertrekpunt: een lagere score is geen oordeel, maar wijst op een mogelijke hefboom voor meer adaptiviteit.",
        "score_interpretation": "Externe vergelijking", "your_interpretation": "Jouw interpretatie", "restart": "Opnieuw invullen",
        "percentile_guide": "De vergelijking toont hoeveel procent van de externe referentiegroep lager scoort. ‘Hoger dan ongeveer 76%’ is dus geen percentage juiste antwoorden.",
        "level_low": "Zeer laag", "level_below_avg": "Eerder laag", "level_average": "Rond het midden", "level_above_avg": "Eerder hoog", "level_high": "Zeer hoog",
    },
    "fr": {
        "title": "Scan systémique de l’adaptabilité", "intro": "Découvrez quels facteurs individuels, collectifs et organisationnels soutiennent ou freinent votre comportement adaptatif.",
        "details_step": "Étape 1 · Vos informations", "details_title": "Parlez-nous brièvement de vous", "details_intro": "Complétez le scan et découvrez ce que vous et votre environnement pouvez faire pour renforcer votre adaptabilité.",
        "name": "Nom", "email": "Adresse e-mail (facultatif)", "email_help": "Nous la conservons uniquement afin de pouvoir éventuellement vous transmettre votre résultat plus tard. Aucun e-mail n’est envoyé maintenant.", "role": "Fonction", "organisation": "Organisation", "start": "Commencer le questionnaire",
        "manager_question": "Supervisez-vous directement des collaborateurs ?", "yes": "Oui", "no": "Non", "manager_required": "Indiquez si vous supervisez directement des collaborateurs.",
        "self_leadership_title": "Votre propre leadership", "self_leadership_intro": "Répondez en pensant à l’équipe que vous dirigez. En tant que responsable...",
        "own_manager_title": "Votre propre responsable", "own_manager_intro": "Nous vous demandons également de répondre à quelques questions concernant votre propre responsable.",
        "self_leadership_result": "Votre leadership adaptatif", "self_leadership_result_intro": "Ce score complémentaire résume la manière dont vous percevez votre propre leadership auprès de l’équipe que vous dirigez.",
        "self_benchmark_unavailable": "Les données de référence externes pour votre propre leadership ne sont pas encore disponibles.", "self_recommendation": "Recommandation", "self_recommendation_text": "Utilisez les trois sous-dimensions comme point de départ du dialogue : consolidez vos points forts et choisissez un comportement concret dans la sous-dimension la moins élevée afin de le développer et de demander du feedback.",
        "part": "Partie {current} sur 3", "part_individual": "Base individuelle", "part_team": "Équipe & responsable", "part_organisation": "Organisation",
        "part_instruction": "Pour chaque affirmation, indiquez dans quelle mesure vous êtes d’accord.", "previous": "Précédent", "next": "Suivant", "show_result": "Afficher mon résultat", "missing": "Répondez à toutes les questions de cette partie.", "complete": "Cette partie est entièrement complétée.",
        "scale": ["Pas du tout d’accord", "Pas d’accord", "Neutre", "D’accord", "Tout à fait d’accord"],
        "profile_pill": "Votre profil systémique", "thanks": "Merci pour votre participation", "result_intro": "Vos résultats montrent quels facteurs individuels, collectifs et organisationnels soutiennent ou freinent aujourd’hui votre comportement adaptatif.",
        "model": "Le modèle global", "stands_out": "Que retenir ?", "strongest": "Facteur de soutien le plus fort", "development": "Principale opportunité de développement",
        "higher_than": "Score supérieur à celui d’environ {p}% du groupe de référence", "lower_context": "Ce facteur est vécu comme relativement moins présent et peut constituer un levier de développement pertinent.",
        "summary_note": "Utilisez surtout le profil à travers les trois niveaux comme point de départ : un score plus faible n’est pas un jugement, mais indique un levier potentiel d’adaptabilité.",
        "score_interpretation": "Comparaison externe", "your_interpretation": "Votre interprétation", "restart": "Recommencer",
        "percentile_guide": "La comparaison indique le pourcentage du groupe de référence externe qui obtient un score inférieur. « Supérieur à environ 76 % » n’est donc pas un pourcentage de bonnes réponses.",
        "level_low": "Très faible", "level_below_avg": "Plutôt faible", "level_average": "Dans la moyenne", "level_above_avg": "Plutôt élevé", "level_high": "Très élevé",
    },
    "en": {
        "title": "Adaptability System Scan", "intro": "Discover which individual, team and organisational factors support or hinder your adaptive behaviour.",
        "details_step": "Step 1 · Your details", "details_title": "Tell us a little about yourself", "details_intro": "Complete the system scan and discover what you and your environment can do to strengthen adaptability.",
        "name": "Name", "email": "Email address (optional)", "email_help": "We only store this so that we may send you your result later. No email is sent now.", "role": "Role", "organisation": "Organisation", "start": "Start questionnaire",
        "manager_question": "Do you directly manage employees?", "yes": "Yes", "no": "No", "manager_required": "Indicate whether you directly manage employees.",
        "self_leadership_title": "Your own leadership", "self_leadership_intro": "Answer with the team you lead in mind.",
        "own_manager_title": "Your own manager", "own_manager_intro": "We also ask you to answer several questions about your own manager.",
        "self_leadership_result": "Your adaptive leadership", "self_leadership_result_intro": "This additional score summarises how you experience your own leadership of the team you manage.",
        "self_benchmark_unavailable": "External benchmark data for your own leadership is not yet available.", "self_recommendation": "Recommendation", "self_recommendation_text": "Use the three subdimensions as a conversation starter: maintain what is already strong and choose one concrete behaviour within the lowest-scoring subdimension to practise further and request feedback on.",
        "part": "Part {current} of 3", "part_individual": "Individual foundation", "part_team": "Team & manager", "part_organisation": "Organisation",
        "part_instruction": "For each statement, indicate how strongly you agree.", "previous": "Previous", "next": "Next", "show_result": "Show my result", "missing": "Answer all questions in this part.", "complete": "This part is complete.",
        "scale": ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        "profile_pill": "Your system profile", "thanks": "Thank you for taking part", "result_intro": "Your results show which individual, team and organisational factors currently support or hinder your adaptive behaviour.",
        "model": "The overarching model", "stands_out": "What stands out?", "strongest": "Strongest supporting factor", "development": "Main development opportunity",
        "higher_than": "Higher than approximately {p}% of the reference group", "lower_context": "This factor is experienced as relatively less present and may be a meaningful development lever.",
        "summary_note": "Use the pattern across the three levels as your starting point: a lower score is not a judgement, but indicates a potential lever for greater adaptability.",
        "score_interpretation": "External comparison", "your_interpretation": "Your interpretation", "restart": "Start again",
        "percentile_guide": "The comparison shows what percentage of the external reference group scored lower. ‘Higher than approximately 76%’ is therefore not a percentage of correct answers.",
        "level_low": "Very low", "level_below_avg": "Rather low", "level_average": "Around the middle", "level_above_avg": "Rather high", "level_high": "Very high",
    },
}

QUESTION_TRANSLATIONS = {
"fr": {
"COM-C1":"Je suis convaincu(e) de pouvoir adapter ma façon de travailler lorsque des changements inattendus surviennent.","COM-C2":" J’ai les compétences nécessaires pour évaluer différentes solutions et choisir la meilleure. ","COM-C3":" Mes expériences passées m’aident à continuer à me développer et à m’adapter. ","COM-C4":" Je considère qu’il est important d’adapter ma façon de travailler lorsque les circonstances changent. ","COM-C5":" Je pense que ma capacité d’adaptation au travail dépend principalement de moi-même plutôt que de mon environnement.","COM-C_new":" Je peux rapidement établir des liens entre différents éléments et garder une vue d’ensemble dans de nouvelles situations.",
"COM-M1":" Les changements me motivent, car ils me donnent l’occasion d’adapter ma façon de travailler.","COM-M2":" Je prends moi-même l’initiative de développer mes connaissances et mes compétences afin de mieux faire face à de nouveaux défis.","COM-M3":" Je suis motivé(e) à essayer de nouvelles façons de travailler, même lorsqu’elles perturbent mes habitudes.","COM-M4":" Mon sentiment d’appartenance à mon organisation me motive à adapter ma façon de travailler lorsque cela est nécessaire.","COM-M5":" J’estime qu’il est de ma responsabilité d’adapter mon travail lorsque la situation change.","COM-M6":" Même lorsque les changements sont difficiles à vivre, je reste motivé(e) à m’adapter.","COM-M7":" Je reste à l’aise dans mon travail, même lorsque les changements ne sont pas encore totalement clairs.","COM-M8R":" Le fait de devoir constamment m’adapter réduit parfois ma motivation.","LO_M":"Je suis motivé(e) à apprendre de nouvelles choses.",
"JobCh_jobins_R":"Je crains que mon travail évolue de manière défavorable (p. ex. moins de variété, moins d’opportunités de développement ou moins d’autonomie).","JobCh_rolinsec1R":"Il est souvent difficile de savoir exactement ce qui est attendu de moi ou ce qui va changer dans mon travail. ","JobCh_rolinsec2":"Il est clair pour moi ce que l’on attend de moi lorsque des changements surviennent.","JobCh_TaskComplex":"Je me sens suffisamment stimulé(e) dans mon travail, sans pour autant être surchargé(e).","JobCh_TaskSign":"Mon travail a un impact positif clair sur des personnes en dehors d’mon organisation.","JobCh_AutonDec":"Mon travail me donne une grande autonomie dans la prise de décisions.","JobCh_AutonMeth":"Je dispose d’une grande liberté et d’une grande autonomie dans la manière dont j’effectue mon travail.","JobCh_Interdep":"Les autres dépendent de mon travail pour pouvoir terminer leurs tâches.",
"AD_TR":"Mon équipe (dont je suis le/la responsable direct(e)) réagit bien aux situations imprévues.","AD_CL":"Mes collègues et moi prenons régulièrement le temps d’améliorer nos méthodes de travail.","AD_F":"Lorsque quelque chose se passe mal, mon équipe adapte sa façon de travailler en fonction de ce qu’elle apprend.","AD_SA":"Face à des situations imprévues, mon équipe recueille activement des informations afin de mieux comprendre ce qui se passe.","COM-O5":"Dans mon équipe, chacun adapte sa façon de travailler en fonction de l’évolution des circonstances.","AD_new1":"Dans mon équipe, nous réfléchissons activement aux changements possibles à l’avenir et à la manière de nous y préparer.","AD_new2":"Dans mon équipe, nous discutons régulièrement des changements futurs possibles (p. ex. en matière de clients, de technologie ou de réglementation) et de ce qu’ils impliquent pour notre travail.",
"AD_HI":"Face à des situations imprévues, nous vérifions systématiquement que les informations sont claires pour tout le monde.","AD_PS":"Dans mon équipe, les personnes expriment ouvertement leur désaccord lorsqu’elles ont une autre opinion sur une solution.","AD_T":"Face à des situations imprévues, il est clair au sein de mon équipe qui fait quoi et ce que l’on attend de chacun.","AD_SL":"En tant qu’équipe, nous considérons qu’il est important de discuter de différentes approches lorsque nous résolvons ensemble des problèmes.","COM-O2":"Mes collègues m’encouragent à tester et à expérimenter de nouvelles idées.","JDSCSS5":"Les personnes avec lesquelles je travaille manifestent un intérêt personnel à mon égard.",
"COM_ADAP1":"Mon responsable encourage la créativité et les nouvelles idées.","COM_ADAP2":"Mon responsable veille à ce que nous apprenions de nos erreurs et puissions progresser ensemble.","COM-O4":"Mon responsable montre l’exemple dans la manière de faire face aux changements.","COM_ADM1":"Mon responsable fixe des objectifs clairs, suis les progrès réalisés et en discute avec notre équipe.","COM_ADM2":"Mon responsable apporte de la structure et de la planification à notre travail.","COM_ENAB1":"Mon responsable crée un environnement dans lequel les membres de l’équipe peuvent discuter ouvertement de points de vue différents.","COM_ENAB2":"Mon responsable aide les membres de l’équipe à créer des liens entre nous afin que nous puissions apprendre les uns des autres.",
"OAP1":"Mon organisation s’adapte efficacement aux évolutions sociales et économiques.","CR_CE1":"Mon organisation poursuit ses efforts d’amélioration continue.","CR_CE3":"Mon organisation assure un suivi structuré des changements et des améliorations.","visie1":"Mon organisation traduit en temps utile les signaux provenant de son environnement (p. ex. le marché, la société ou la technologie) en choix concrets ou en formes de soutien (p. ex. priorités, compétences ou approche).",
"OL_MC1":"La direction d’mon organisation implique souvent les collaborateurs dans les décisions importantes.","OL_MC2R":"La direction considère davantage l’apprentissage comme un coût que comme un investissement.","OL_MC3":"La direction d’mon organisation est favorable aux changements qui nous permettent de nous adapter aux évolutions externes ou de les anticiper.","visie2":"Je comprends clairement où mon organisation souhaite aller à l’avenir et ce que cela implique pour mon travail.",
"CR_CE2":"Mon organisation parvient à motiver les collaborateurs à adapter leur façon de travailler aux nouvelles circonstances.","CR_K1":"Mon organisation sait comment soutenir les collaborateurs afin qu’ils continuent à apprendre et à s’adapter.","CR_K2":"Mon organisation a une vision claire de ce qui est nécessaire pour s’adapter aux évolutions de son environnement.","CR_A1":"Mon organisation dispose des ressources nécessaires pour s’adapter aux changements.","CR_A2":"Mon organisation offre aux collaborateurs la possibilité d’apprendre et de se développer.","CR_A3":"Mon organisation accorde suffisamment de temps pour me permettre de me préparer aux changements ou de m’y adapter.","OL_KT2":"Mon organisation dispose d’outils (guides, procédures, bases de données) permettant de préserver les connaissances acquises, même lorsque les collaborateurs changent.","OL_S1":"Tous les niveaux d’mon organisation (p. ex. département, équipe, individu) comprennent clairement comment ils contribuent aux objectifs généraux.","OL_S2":"Tous les niveaux d’mon organisation sont interconnectés et collaborent efficacement les uns avec les autres.","AD_CD":"Lorsque nous collaborons avec d’autres équipes, il est clair qui est responsable de quelles décisions.",
"OL_O1":"Mon organisation encourage l’expérimentation et l’innovation afin d’améliorer les processus.","OL_O2":"Mon organisation observe ce que font les autres organisations et adopte les idées qui peuvent lui être utiles.","OL_O3":"Les idées et les expériences des partenaires externes (p. ex. consultants ou clients) sont considérées comme une source précieuse d’apprentissage.","OL_O4":"Il fait partie de la culture d’mon organisation que les collaborateurs partagent leurs idées et leurs points de vue sur la manière d’améliorer les processus de travail.","OL_MC4":"Les nouvelles idées qui donnent de bons résultats sont valorisées. ","OL_KT1":"Les erreurs sont discutées et analysées à tous les niveaux de l’organisation.","HR_Train":"Il existe chez mon organisation des formations visant à aider les collaborateurs à mieux s’adapter aux changements.","HR_Comp":"Les collaborateurs qui adoptent une attitude très proactive face au changement bénéficient d’opportunités ou de récompenses supplémentaires.","HR_PerfApp":"Les entretiens d’évaluation et de développement portent également sur le développement des compétences liées au changement.","HR_Selec":"Lors du recrutement, nous tenons compte de la capacité des candidats à bien s’adapter aux changements."
},
"en": {
"COM-C1":"I am confident that I can adapt the way I work when unexpected changes occur.","COM-C2":"I have the skills to assess different solutions and choose the best one.","COM-C3":"My previous experiences help me continue to grow and adapt.","COM-C4":"I consider it important to adjust the way I work when circumstances change.","COM-C5":"I feel that my adaptability at work mainly depends on me rather than my environment.","COM-C_new":"I can quickly identify connections and maintain an overview in new situations.",
"COM-M1":"Changes motivate me because they offer opportunities to adjust the way I work.","COM-M2":"I take the initiative to renew my knowledge and skills so that I can deal better with new challenges.","COM-M3":"I am motivated to try new ways of working, even when they disrupt my routine.","COM-M4":"The connection I feel with my organisation motivates me to adapt the way I work when needed.","COM-M5":"I see it as my responsibility to adapt my work when the situation changes.","COM-M6":"Even when changes feel demanding, I remain motivated to adapt.","COM-M7":"I feel comfortable continuing my work even when changes are not yet completely clear.","COM-M8R":"The constant need to adapt sometimes reduces my motivation.","LO_M":"I am motivated to learn new things.",
"JobCh_jobins_R":"I fear that my job will change for the worse, for example through less variety, development opportunity or freedom.","JobCh_rolinsec1R":"In my work, it is often unclear what exactly is expected or what will change.","JobCh_rolinsec2":"It is clear what is expected of me when changes occur.","JobCh_TaskComplex":"I feel sufficiently challenged, but not overloaded, in my work.","JobCh_TaskSign":"My work has a clear positive impact on people outside my organisation.","JobCh_AutonDec":"My job gives me considerable autonomy in making decisions.","JobCh_AutonMeth":"My job gives me a great deal of freedom and independence in how I do my work.","JobCh_Interdep":"Unless my work is completed, others cannot finish their tasks.",
"AD_TR":"My team responds well to unexpected situations.","AD_CL":"My colleagues and I regularly take time to improve our working methods.","AD_F":"When something goes wrong, my team adapts the way we work based on what we learn.","AD_SA":"In unexpected situations, my team actively gathers information to better understand what is happening.","COM-O5":"Everyone in my team adjusts the way they work when circumstances change.","AD_new1":"In my team, we actively consider possible future changes and how we can prepare for them.","AD_new2":"In my team, we regularly discuss future changes that may affect us, such as changes in customers, technology or regulation, and what they mean for our work.",
"AD_HI":"In unexpected situations, we double-check that the information is clear to everyone.","AD_PS":"People in my team speak honestly when they disagree about a solution.","AD_T":"In unexpected situations, it is clear within my team who does what and what is expected of each person.","AD_SL":"As a team, we consider it important to discuss different approaches when solving problems together.","COM-O2":"My colleagues encourage me to test and try new ideas.","JDSCSS5":"The people I work with take a personal interest in me.",
"COM_ADAP1":"My manager encourages creativity and new ideas.","COM_ADAP2":"My manager ensures that we learn from mistakes and can grow together.","COM-O4":"My manager sets a good example in dealing with change.","COM_ADM1":"My manager sets clear goals, measures progress and discusses it.","COM_ADM2":"My manager provides structure and planning in our work.","COM_ENAB1":"My manager creates a setting in which team members can openly discuss different opinions.","COM_ENAB2":"My manager helps team members connect so that we can learn from one another.",
"OAP1":"My organisation adapts effectively to social and economic changes.","CR_CE1":"My organisation continuously works on improvement.","CR_CE3":"My organisation systematically monitors the progress of changes and improvements.","visie1":"My organisation translates signals from its environment, such as market, society or technology, into timely choices or support.",
"OL_MC1":"Top management often involves employees in important decisions.","OL_MC2R":"In my organisation, management sees learning more as a cost than an investment.","OL_MC3":"Top management supports changes that allow us to keep pace with or stay ahead of external developments.","visie2":"I clearly understand where our organisation wants to go in the future and what this means for my work.",
"CR_CE2":"My organisation succeeds in motivating people to adapt the way they work to new circumstances.","CR_K1":"My organisation knows how to support employees in continuing to learn and adapt.","CR_K2":"My organisation has a clear understanding of what is needed to adapt to changes in its environment.","CR_A1":"My organisation has sufficient resources to adapt to change.","CR_A2":"My organisation gives employees room to learn and grow.","CR_A3":"My organisation gives me enough time to prepare for or adapt to changes.","OL_KT2":"My organisation has tools, such as manuals, routines and databases, to preserve knowledge from the past even when colleagues change.","OL_S1":"All levels of the organisation know how they contribute to the overall goals.","OL_S2":"All levels of the organisation are connected and work well together.","AD_CD":"When we work with other teams, it is clear who should make which decisions.",
"OL_O1":"My organisation encourages experimentation and innovation to improve processes.","OL_O2":"My organisation looks at what other organisations do and adopts useful ideas.","OL_O3":"Ideas and experiences from external partners, such as advisers or customers, are considered valuable sources of learning.","OL_O4":"Sharing opinions and ideas about improving work processes is part of our organisational culture.","OL_MC4":"New ideas that work well are rewarded.","OL_KT1":"Mistakes are discussed and analysed at every level of the organisation.","HR_Train":"My organisation provides training to help employees adapt better to change.","HR_Comp":"Employees who deal with change very proactively receive additional opportunities or rewards.","HR_PerfApp":"Performance reviews focus on developing change-related skills.","HR_Selec":"When recruiting, we consider how well candidates can adapt."
}}

SELF_LEADERSHIP_TRANSLATIONS = {
"nl": {
"SELF_COM_ADAP1":"Ik stimuleer creativiteit en nieuwe ideeën in mijn team.","SELF_COM_ADAP2":"Ik zorg dat we leren van fouten en samen kunnen groeien.","SELF_COM-O4":"Ik geef het goede voorbeeld in hoe om te gaan met veranderingen.","SELF_COM_ADM1":"Ik stel duidelijke doelen, meet voortgang én bespreek deze met mijn team.","SELF_COM_ADM2":"Ik geef structuur en planning aan het werk van mijn team.","SELF_COM_ENAB1":"Ik creëer een context waarin teamleden verschillende meningen openlijk kunnen bespreken.","SELF_COM_ENAB2":"Ik help teamleden met elkaar te verbinden zodat ze van elkaar kunnen leren."},
"fr": {
"SELF_COM_ADAP1":"J’encourage la créativité et les nouvelles idées.","SELF_COM_ADAP2":"Je veille à ce que nous apprenions de nos erreurs et que nous puissions progresser ensemble.","SELF_COM-O4":"Je montre l’exemple dans la manière de faire face aux changements.","SELF_COM_ADM1":"Je fixe des objectifs clairs, je suis les progrès réalisés et j’en discute avec mon équipe.","SELF_COM_ADM2":"J’apporte de la structure et de la planification à notre travail.","SELF_COM_ENAB1":"Je crée un environnement dans lequel les membres de l’équipe peuvent discuter ouvertement de points de vue différents.","SELF_COM_ENAB2":"J’aide les membres de l’équipe à créer des liens entre eux afin que nous puissions apprendre les uns des autres."},
"en": {
"SELF_COM_ADAP1":"I encourage creativity and new ideas in my team.","SELF_COM_ADAP2":"I ensure that we learn from mistakes and can grow together.","SELF_COM-O4":"I set a good example in how to deal with change.","SELF_COM_ADM1":"I set clear goals, measure progress and discuss it with my team.","SELF_COM_ADM2":"I provide structure and planning for my team’s work.","SELF_COM_ENAB1":"I create a setting in which team members can openly discuss different opinions.","SELF_COM_ENAB2":"I help team members connect so that they can learn from one another."}}

DIMENSION_LABELS = {
"nl":{"Capaciteit":"Capaciteit","Motivatie":"Motivatie","Job Karakteristieken":"Jobkarakteristieken","Teamadaptiviteit":"Teamadaptiviteit","Teamklimaat":"Teamklimaat","Richting & steun leidinggevende":"Directe leidinggevende","Organisatieadaptiviteit":"Organisatieadaptiviteit","Richting & steun van organisatie":"Richting & steun van organisatie","Organisatieklimaat":"Organisatieklimaat","HR":"HR-beleid"},
"fr":{"Capaciteit":"Capacité","Motivatie":"Motivation","Job Karakteristieken":"Caractéristiques du poste","Teamadaptiviteit":"Adaptabilité de l’équipe","Teamklimaat":"Climat d’équipe","Richting & steun leidinggevende":"Responsable direct","Organisatieadaptiviteit":"Adaptabilité organisationnelle","Richting & steun van organisatie":"Orientation & soutien de l’organisation","Organisatieklimaat":"Climat organisationnel","HR":"Politique RH"},
"en":{"Capaciteit":"Capability","Motivatie":"Motivation","Job Karakteristieken":"Job characteristics","Teamadaptiviteit":"Team adaptability","Teamklimaat":"Team climate","Richting & steun leidinggevende":"Direct manager","Organisatieadaptiviteit":"Organisational adaptability","Richting & steun van organisatie":"Organisational direction & support","Organisatieklimaat":"Organisational climate","HR":"HR policy"}}

SHORT_DESCRIPTIONS = {
"nl":{"Capaciteit":"Vaardigheden, vertrouwen en inzicht om effectief te handelen in nieuwe of complexe situaties.","Motivatie":"Energie, bereidheid en volharding om met verandering om te gaan.","Job Karakteristieken":"Jobkenmerken die aanpassen, leren en flexibel handelen ondersteunen of bemoeilijken.","Teamadaptiviteit":"Hoe flexibel het team reageert, samen leert en zijn werkwijze bijstuurt.","Teamklimaat":"Open communicatie, vertrouwen, veiligheid en duidelijke samenwerking binnen het team.","Richting & steun leidinggevende":"Hoe de leidinggevende vernieuwing, structuur en verbinding ondersteunt.","Organisatieadaptiviteit":"Hoe effectief de organisatie signalen oppikt, leert en zich aanpast.","Richting & steun van organisatie":"Duidelijke richting, kennis, middelen en afstemming om verandering te ondersteunen.","Organisatieklimaat":"Ruimte voor experimenteren, innovatie, leren en het delen van ideeën.","HR":"Hoe HR-praktijken adaptiviteit ondersteunen via selectie, ontwikkeling, evaluatie en waardering."},
"fr":{"Capaciteit":"Compétences, confiance et compréhension nécessaires pour agir dans des situations nouvelles ou complexes.","Motivatie":"Énergie, volonté et persévérance face au changement.","Job Karakteristieken":"Caractéristiques du poste qui facilitent ou freinent l’apprentissage et l’adaptation.","Teamadaptiviteit":"La manière dont l’équipe réagit avec souplesse, apprend et ajuste son fonctionnement.","Teamklimaat":"Communication ouverte, confiance, sécurité et collaboration claire.","Richting & steun leidinggevende":"La façon dont le responsable soutient l’innovation, la structure et les liens.","Organisatieadaptiviteit":"La capacité de l’organisation à capter les signaux, apprendre et s’adapter.","Richting & steun van organisatie":"Orientation claire, connaissances, moyens et coordination pour soutenir le changement.","Organisatieklimaat":"Espace accordé à l’expérimentation, l’innovation, l’apprentissage et au partage d’idées.","HR":"Soutien de l’adaptabilité par la sélection, le développement, l’évaluation et la reconnaissance."},
"en":{"Capaciteit":"Skills, confidence and insight needed to act effectively in new or complex situations.","Motivatie":"Energy, willingness and persistence in dealing with change.","Job Karakteristieken":"Job features that support or hinder learning and flexible action.","Teamadaptiviteit":"How flexibly the team responds, learns together and adjusts its way of working.","Teamklimaat":"Open communication, trust, safety and clear collaboration within the team.","Richting & steun leidinggevende":"How the manager supports innovation, structure and connection.","Organisatieadaptiviteit":"How effectively the organisation picks up signals, learns and adapts.","Richting & steun van organisatie":"Clear direction, knowledge, resources and alignment to support change.","Organisatieklimaat":"Room for experimentation, innovation, learning and sharing ideas.","HR":"How HR practices support adaptability through selection, development, evaluation and recognition."}}

GROUP_TEXTS = {
"nl":{"Individuele basis":"Je persoonlijke basis voor adaptiviteit: wat je kan, wat je motiveert en hoe je job is ingericht.","Team & leidinggevende":"De dagelijkse context waarin samenwerking, veiligheid, leren en leiding jouw adaptiviteit versterken of afremmen.","Organisatie":"De bredere richting, systemen, cultuur en ondersteuning die duurzaam aanpassen en leren mogelijk maken."},
"fr":{"Individuele basis":"Votre base personnelle : ce que vous pouvez faire, ce qui vous motive et la manière dont votre poste est conçu.","Team & leidinggevende":"Le contexte quotidien dans lequel collaboration, sécurité, apprentissage et leadership renforcent ou freinent votre adaptabilité.","Organisatie":"L’orientation, les systèmes, la culture et le soutien qui rendent possible une adaptation durable."},
"en":{"Individuele basis":"Your personal foundation: what you can do, what motivates you and how your job is designed.","Team & leidinggevende":"The daily context in which collaboration, safety, learning and leadership support or hinder adaptability.","Organisatie":"The wider direction, systems, culture and support that enable sustainable adaptation and learning."}}

GROUP_LABELS = {
"nl":{"Individuele basis":"Individuele basis","Team & leidinggevende":"Teamuitkomsten","Organisatie":"Organisatiefactoren"},
"fr":{"Individuele basis":"Base individuelle","Team & leidinggevende":"Résultats de l’équipe","Organisatie":"Facteurs organisationnels"},
"en":{"Individuele basis":"Individual foundation","Team & leidinggevende":"Team outcomes","Organisatie":"Organisational factors"}}

SUBDIMENSION_LABELS = {
"nl":{},
"fr":{"Perceived Behavioral Control":"Contrôle comportemental perçu","Vaardigheid":"Compétences","Ervaren belang":"Importance perçue","Intrinsieke motivatie":"Motivation intrinsèque","Betrokkenheid":"Engagement","Volharding":"Persévérance","Job onzekerheid":"Insécurité d’emploi","Rolduidelijkheid":"Clarté du rôle","Taakcomplexiteit & betekenis":"Complexité & sens des tâches","Autonomie":"Autonomie","Afhankelijkheid":"Interdépendance","Nieuwigheden stimuleren":"Stimuler l’innovation","Structuur aanbrengen":"Apporter de la structure","Verbinding maken":"Créer des liens","Topmanagement steun":"Soutien de la direction","Kennis":"Connaissances","Middelen":"Ressources","Alignment":"Alignement"},
"en":{"Perceived Behavioral Control":"Perceived behavioural control","Vaardigheid":"Skills","Ervaren belang":"Perceived importance","Intrinsieke motivatie":"Intrinsic motivation","Betrokkenheid":"Commitment","Volharding":"Persistence","Job onzekerheid":"Job insecurity","Rolduidelijkheid":"Role clarity","Taakcomplexiteit & betekenis":"Task complexity & meaning","Autonomie":"Autonomy","Afhankelijkheid":"Interdependence","Nieuwigheden stimuleren":"Encouraging innovation","Structuur aanbrengen":"Providing structure","Verbinding maken":"Building connection","Topmanagement steun":"Top-management support","Kennis":"Knowledge","Middelen":"Resources","Alignment":"Alignment"}}

INTERPRETATIONS = {
"fr":{"individual":{"low":"Cette caractéristique est actuellement moins présente et peut compliquer l’adaptation aux nouvelles situations.","below_avg":"Cette caractéristique est un peu moins présente que dans le groupe de référence et offre une marge de développement.","average":"Cette caractéristique constitue une base comparable à celle de la plupart des personnes du groupe de référence.","above_avg":"Cette caractéristique soutient relativement bien votre capacité à faire face au changement.","high":"Cette caractéristique constitue clairement un point fort de votre adaptabilité au travail."},"context":{"low":"Vous vivez ce contexte comme nettement moins soutenant que la plupart des personnes du groupe de référence.","below_avg":"Vous vivez ce contexte comme un peu moins soutenant ; certaines conditions favorables semblent moins présentes.","average":"Votre environnement offre un niveau de soutien comparable à celui du groupe de référence.","above_avg":"Vous vivez ce contexte comme relativement soutenant pour l’apprentissage et le changement.","high":"Vous vivez ce contexte comme très soutenant pour l’adaptabilité, l’apprentissage et le changement."}},
"en":{"individual":{"low":"This characteristic is currently less present and may make it harder to adapt to new situations.","below_avg":"This characteristic is somewhat less present than in the reference group and offers room for development.","average":"This characteristic provides a foundation similar to that of most people in the reference group.","above_avg":"This characteristic supports your ability to deal with change relatively well.","high":"This characteristic is clearly a strength in your adaptability at work."},"context":{"low":"You experience this context as considerably less supportive than most people in the reference group.","below_avg":"You experience this context as somewhat less supportive; some enabling conditions appear less present.","average":"Your environment provides a level of support similar to that of the reference group.","above_avg":"You experience this context as relatively supportive of learning and change.","high":"You experience this context as highly supportive of adaptability, learning and change."}}}
